# Author: Laura Fachal
# Institution: Wellcome Sanger Institute
# ORCID: https://orcid.org/0000-0002-7256-9752
#
# reformat_soskic_data

# ## blagoje's data:
# singularity exec iibdgc_postprocess_10_singularity.sif
path_gwas=/path/to/ibdgwas/IIBDGC/
cd ${path_gwas}post_imputation/2022/analysis/metaanalysis/annotation/soskic_2019/
  
# tar -czvf peaks_normalized_to_max.tgz PEAKS_NORMALIZED_TO_MAX/
# tar -czvf peaks.tgz PEAKS/
  

# cd ${path_gwas}post_imputation/2022/analysis/metaanalysis/annotation/soskic_2019/
# tar -xvf peaks.tgz
# tar -xvf peaks_normalized_to_max.tgz
  
# emacs README
# # files generated by Blagoje Soskic as part of their paper https://www.ncbi.nlm.nih.gov/pubmed/31548716
# # PEAKS/ folder includes the read counts per consensus peak
# # PEAKS_NORMALIZED_TO_MAX/ where Blagoje normalized each peak by scaling the read counts to the sample with the highest count


# ### ATAC SEQ READS

cd ${path_gwas}post_imputation/2022/analysis/metaanalysis/annotation/soskic_2019/PEAKS/ATAC/
files_atac=($(ls | sed 's/\.txt//g' ))

echo ${#files_atac[@]}
# 55

for i in ${files_atac[@]}
do echo ${i}
done

# intersect, add header and  replace . by 0
MEM=1000
for i in ${files_atac[@]}
do 
bsub -J"ldsc_intersect" -M"$MEM" -R"select[mem>$MEM] rusage[mem=$MEM] span[hosts=1]" -G your_hpc_group \
-e ${path_gwas}post_imputation/log/allchr_${i}_subset_eur_tier2_rate_0.5_stderr \
-o ${path_gwas}post_imputation/log/allchr_${i}_subset_eur_tier2_rate_0.5_stdout \
"bedtools intersect -a ${path_gwas}post_imputation/2022/analysis/metaanalysis/annotation/list_union_variants_cd_uc_ibd_eur_tier2_metaanalysis_rate_0.5_info_0.9_sorted.bed \
-b ${path_gwas}post_imputation/2022/analysis/metaanalysis/annotation/soskic_2019/PEAKS/ATAC/${i}.txt \
-loj | cut -f 4,8 | awk -F'\\t' -v OFS='\\t' 'BEGIN {print \"variant\",\"'\"${i}\"'\"}1' | sed 's/\\t\./\\t0/gm'| gzip > ${path_gwas}post_imputation/2022/analysis/metaanalysis/annotation/soskic_2019/PEAKS/ATAC/allchr_${i}_b38_list_union_variants_cd_uc_ibd_eur_tier_2_metaanalysis_eur_tier2_rate_0.5.bed.gz"
done

for i in ${files_atac[@]}
do 
echo ${i} && tail -30 ${path_gwas}post_imputation/log/allchr_${i}_subset_eur_tier2_rate_0.5_stdout | grep "Successfully"
done

# double-check
for i in ${files_atac[@]}
do 
echo ${i} && zcat ${path_gwas}post_imputation/2022/analysis/metaanalysis/annotation/soskic_2019/PEAKS/ATAC/allchr_${i}_b38_list_union_variants_cd_uc_ibd_eur_tier_2_metaanalysis_eur_tier2_rate_0.5.bed.gz | wc -l
done

# remove intermediate files:
rm ${path_gwas}post_imputation/2022/analysis/metaanalysis/annotation/soskic_2019/PEAKS/ATAC/*_tmp.bed

# mv data to final folder
mv ${path_gwas}post_imputation/2022/analysis/metaanalysis/annotation/soskic_2019/PEAKS/ATAC/allchr_*_b38_list_union_variants_cd_uc_ibd_eur_tier_2_metaanalysis_eur_tier2_rate_0.5.bed.gz \
/path/to/ibdgwas/IIBDGC/post_imputation/2022/analysis/metaanalysis/annotation/matrix/individual_files/files_version_april2025/
  

  
# ### H3K27ac SEQ READS
  
cd ${path_gwas}post_imputation/2022/analysis/metaanalysis/annotation/soskic_2019/PEAKS/H3K27ac/
files_hist=($(ls | grep -v 'list_union_variants' | sed 's/\.txt//g' ))

echo ${#files_hist[@]}
# 55

for i in ${files_hist[@]}
do echo ${i}
done

# intersect, add header and  replace . by 0
MEM=1000
for i in ${files_hist[@]}
do 
bsub -J"ldsc_intersect" -M"$MEM" -R"select[mem>$MEM] rusage[mem=$MEM] span[hosts=1]" -G your_hpc_group \
-e ${path_gwas}post_imputation/log/allchr_${i}_subset_eur_tier2_rate_0.5_stderr \
-o ${path_gwas}post_imputation/log/allchr_${i}_subset_eur_tier2_rate_0.5_stdout \
"bedtools intersect -a ${path_gwas}post_imputation/2022/analysis/metaanalysis/annotation/list_union_variants_cd_uc_ibd_eur_tier2_metaanalysis_rate_0.5_info_0.9_sorted.bed \
-b ${path_gwas}post_imputation/2022/analysis/metaanalysis/annotation/soskic_2019/PEAKS/H3K27ac/${i}.txt \
-loj | cut -f 4,8 | awk -F'\\t' -v OFS='\\t' 'BEGIN {print \"variant\",\"'\"${i}\"'\"}1' | sed 's/\\t\./\\t0/gm'| gzip > ${path_gwas}post_imputation/2022/analysis/metaanalysis/annotation/soskic_2019/PEAKS/H3K27ac/allchr_${i}_b38_list_union_variants_cd_uc_ibd_eur_tier_2_metaanalysis_eur_tier2_rate_0.5_info_0.9_subset.bed.gz"
done

# CONTINUE HERE


for i in ${files_hist[@]}
do 
echo ${i} && tail -30 ${path_gwas}post_imputation/log/allchr_${i}_subset_eur_tier2_rate_0.5_stdout | grep "Successfully"
done


# double-check
for i in ${files_hist[@]}
do 
echo ${i} && zcat ${path_gwas}post_imputation/2022/analysis/metaanalysis/annotation/soskic_2019/PEAKS/H3K27ac/allchr_${i}_b38_list_union_variants_cd_uc_ibd_eur_tier_2_metaanalysis_eur_tier2_rate_0.5_info_0.9_subset.bed.gz | wc -l
done


# remove intermediate files:
rm ${path_gwas}post_imputation/2022/analysis/metaanalysis/annotation/soskic_2019/PEAKS/H3K27ac/*_tmp.bed

# mv data to final folder
mv ${path_gwas}post_imputation/2022/analysis/metaanalysis/annotation/soskic_2019/PEAKS/H3K27ac/allchr_*_b38_list_union_variants_cd_uc_ibd_eur_tier_2_metaanalysis_eur_tier2_rate_0.5_info_0.9_subset.bed.gz \
/path/to/ibdgwas/IIBDGC/post_imputation/2022/analysis/metaanalysis/annotation/matrix/individual_files/files_version_april2025/
  



